In [1]:
# Tensor Flow: a tensor is a N dimensional array of data
# Rank 0 Tensor: scalar
# Rank 1 Tensor: vector
# Rank 2 Tensor: matrix
# Rank 3 Tensor
# Rank 4 Tensor

In [2]:
import os

In [3]:
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [5]:
pip install tensorflow

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  Created wheel for jax: filename=jax-0.4.8-py3-none-any.whl size=1439795 sha256=eca89c3ba6faf6a31804fb82866bf1a9bc00bba0a0012695703ac39485bb6857
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\45\83\1e\3db22c5e1941c10e41c4f5cdf829b0a358146d4d0733d4a105
Successfully built jax
  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.1
    Uninstalling numpy-1.20.1:
      Successfully uninstalled numpy-1.20.1
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 3.10.0
    Uninstalling importlib-metadata-3.10.0:
      Successfully uninstalled importlib-metadata-3.10.0
  Attempting uninstall: scipy
    Found

In [18]:
import tensorflow as tf
import keras as keras

In [ ]:
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

# Initialization of tensors:

In [9]:
x= tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [10]:
# initialization of tensors:
x= tf.constant(4, shape=(1,1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [11]:
x = tf.constant([[1,2,3], [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [13]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [15]:
x = tf.eye(3)   # identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [16]:
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[ 0.8643981  -2.0938907   0.5377881 ]
 [ 0.04787952 -1.5601741   0.3790472 ]
 [ 0.79739463 -0.33483505  2.3164008 ]], shape=(3, 3), dtype=float32)


In [17]:
x = tf.random.uniform((1,3), minval=0, maxval=1)
print(x)

tf.Tensor([[0.74313664 0.7734195  0.68207717]], shape=(1, 3), dtype=float32)


In [19]:
x = tf.range(start=1, limit=10, delta=2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [21]:
x = tf.cast(x, dtype=tf.float64)                       # floating datatype
print(x) 

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


# Mathematical Operations:

In [22]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [25]:
z = tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [27]:
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [29]:
z = tf.tensordot(x,y,axes=1)            # dot multiplication and then adding the result
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [30]:
z = tf.reduce_sum(x*y, axis=0)          # another way of dot multiplication and then adding the result
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [32]:
z = x ** 5                             # element wise exponential multiplication
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [34]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)

tf.Tensor(
[[ 0.37444156 -0.0199741  -2.1347907  -0.9386397 ]
 [ 1.2641892  -0.3514594   0.37159592 -0.812023  ]], shape=(2, 4), dtype=float32)


In [35]:
z = x@y
print(z)

tf.Tensor(
[[ 0.37444156 -0.0199741  -2.1347907  -0.9386397 ]
 [ 1.2641892  -0.3514594   0.37159592 -0.812023  ]], shape=(2, 4), dtype=float32)


# Indexing:

In [36]:
x = tf.constant([0,1,1,2,3,1,2,3])

In [37]:
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [38]:
print(x[1:])                   # excluding the first element

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [39]:
print(x[1:3])                  # excluding the first as well as the 4th element

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [41]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [44]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [45]:
indices = tf.constant([0,3])             # we get output of only 0th and the 3rd element of the list
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [46]:
x = tf.constant([[1,2],[3,4], [5,6]])

In [47]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [48]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# Reshaping:

In [49]:
x = tf.range(9)

In [50]:
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [51]:
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [52]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
